services:
  auth-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auth-db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
    restart: unless-stopped

volumes:
  db_data: