services:
  link-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: link-db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  link-service:
    build: .
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - link-db
    restart: unless-stopped

volumes:
  db_data: